### ISSUE TITLE
patent landscaping pruning

### ISSUE THREAD

**Issue by sfd9898** [google/patents-public-data#19]
Hello,

It looks like the patent landscape notebook doesn't get all the way through the l1 and l2 expansion and pruning described in the paper. Based on the paper alone, I'm not sure how to try to re-produce these steps for my own seed set. Do you have additional documentation available?

Thanks!

**Comment by seinberg** [comment]
Hi,

Thanks for the question. The code in the notebook is really just a proof of concept to guide in the creation of full landscapes. The code you want to look at for expansion is in expansion.py ([here](https://github.com/google/patents-public-data/blob/ef5f83f4a281f97a4a3b6f19c9d309ead02349d7/models/landscaping/expansion.py#L515)). That's the code that takes only a small subset of all patents for inference.

If the notebook isn't getting through the L1 and L2 expansion, what's probably happening is that the levels of expansion are just too large to fit into memory or to be serialized. You could try removing the serialization sections of the code, but when you re-run it it's going to re-query and do all that work again instead of caching it locally.

Hope that's helpful.

Thanks.

**Comment by sfd9898** [comment]
Hello,

Yes, it's getting through the L1 and L2 expansion. (I can see the l1_patents_df and l2_patents_df). But it's not clear to me where in the code the pruning is happening?

Or would you iterate through the L1 and L2 patents with the model and predict the class of each patent?

Thanks!

**Comment by sfd9898** [comment]
Hello, just to close out. I did end up iterating through the entire L1 and L2 and it seemed to work well.

Thanks!

**Comment by seinberg** [comment]
Great, clad to hear!

**Comment by peiyu-wang** [comment]
Hi @sfd9898 , do you think you can help on this one https://github.com/google/patents-public-data/issues/47?
The model gets deleted on cloud storage, I really want to try the model. I will be super appreciated if you can share the local copy of the models to me if you still have it. Thanks a lot!
